version: "3"

services:

  tg-gpt-proxy:
    image: tg-gpt-proxy
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_HOST=0.0.0.0
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
    command: python main.py
    network_mode: host
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    #    volumes:
    #      - ./src:/src
    #      - ./tests:/tests
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
