"""migration

Revision ID: de0fb3bc5952
Revises: bb91a01aa236
Create Date: 2023-08-11 18:50:31.572005

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de0fb3bc5952"
down_revision = "bb91a01aa236"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_counter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("remain_per_day", sa.Integer(), nullable=True),
        sa.Column("remain_per_all_time", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "out_tg_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("text_like", sa.String(), nullable=True),
        sa.Column("not_pushed_to_delete", sa.Boolean(), nullable=True),
        sa.Column("not_pushed_to_edit_text", sa.String(), nullable=True),
        sa.Column("pushed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tg_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_table(
        "tg_user_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=True),
        sa.Column("state_map", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tg_user_state")
    op.drop_table("tg_user")
    op.drop_table("out_tg_message")
    op.drop_table("access_counter")
    # ### end Alembic commands ###
